service: lnau24-upload

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

functions:
  lambda:
    handler: handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors:
            headers:
              - Content-Type
              - auth-token
              - access-key
      - http:
          path: graphql
          method: get
          cors:
            headers:
              - Content-Type
              - auth-token
              - access-key
